# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: stable
# 指定缓存模块，可选。缓存可加快编译速度。
cache: false

branches:
  only:
    - master

#在构建之前安装hexo环境
before_install:
  - npm install -g hexo-cli
#安装git插件和搜索功能插件
install:
  - npm install
  - npm install hexo-deployer-git --save

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
before_script:
  - git config user.name "Forrest Mi"
  - git config user.email "lishtys@gmail.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
  - hexo deploy

  # - sed -i "s/code_token/${Coding_Token}/g" ./_config.yml
  # - sed -i "s/baidu_token/${baidu_url_token}/g" ./_config.yml
  # - sed -i'' "s~https://github.com/<YOUR NAME>/<YOUR BLOG REPO>.git~https://${ACCESS_TOKEN}@github.com/<YOUR NAME>/<YOUR REPO>.git~" _config.yml
  # - cat ./_config.yml
  # - hexo deploy
# End: Build LifeCycle

