# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Chen Mi 
subtitle: 
description: 
author:  Chen(Forrest) Mi
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://chenmi.ink
root: /
permalink: posts/:abbrlink/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: # Open external links in new tab
  enable: true
  field: post
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'empty'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

index_generator:
  per_page: 10

archive_generator:
  per_page: 20
  yearly: true
  monthly: true
  
category_generator:
  per_page: 10

tag_generator:
  per_page: 10
 
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: https://gh_token@github.com/lishtys/lishtys.github.io.git
    branch: master
# - type: git
#   repo: https://dt_ZeHhtS:code_token@git.dev.tencent.com/lishtys/lishtys.git
#   branch: master
# - type: baidu_url_submitter


server:
  port: 4001
  compress: true
  header: true


# Menus
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  Profile: profile
  
sitemap: 
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml

baidu_url_submit:
  count: 10 
  host: chenmi.ink 
  token: baidu_token 
  path: baidu_urls.txt 


    
# mermaid chart
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "7.1.2" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    #startOnload: true  // default true

# works data
works:
  - name: Pili_Incredible
    title: Pili Incredible
    thumb: https://chenmi-ink-1252570167.cos.na-siliconvalley.myqcloud.com/_Works/PiliCover.JPG
    description: 'Pili Incredible is a online RPG game based on a glove puppetry show from Taiwan. The TV series debuted in 1985, and it still continues today. The game has been shipped in 2016 in Taiwan, entered Apple Store bestseller top 10.'
    page: https://pli.wegames.com.tw/
    detail: /portfolio/Pili_Incredible.html
    youtube: https://www.youtube.com/watch?v=JB6LjrGF0Tc
    tag: product
      
  - name: Era_War
    title: Era War 
    thumb: https://chenmi-ink-1252570167.cos.na-siliconvalley.myqcloud.com/_Works/WarEra_Cover.jpg
    description: 'The game is a MMOARPG mobile game developed in Unity, shipped in 2018. Each occupation has multiple skill genres, and a player can freely transfer skills according to their own needs, experience the fun of crazy bosses in PVP and PVE battles.'
    page: http://zhjy.ingcle.com/
    youtube: https://www.youtube.com/watch?v=6N3AbiD-U6Y
    detail: /portfolio/Era_War.html
    tag: product
  
  - name: The_Surgery_Checklist
    title: The Surgery Checklist
    thumb: https://chenmi-ink-1252570167.cos.na-siliconvalley.myqcloud.com/_Works/SurgeryChecklist_Cover.PNG
    description: 'We’ve created Surgery Checklist, a software suite for iOS and PC, that adds more features, and corrects many of the problems inherent to the paper checklist.'
    detail: /portfolio/Surgery_Checklist.html
    youtube: https://www.youtube.com/watch?v=9_tmlpfFZcg
    tag: product
    
  - name: Kinect_Virtual_Lab
    title: Kinect Virtual Lab
    thumb: https://chenmi-ink-1252570167.cos.na-siliconvalley.myqcloud.com/_Works/Kinect Cover.png
    description: ' By further analyzing and processing the image data that Kinect sensor has obtained, it gets spatial coordinates information, skeleton data and other information to track user’s body joints to recognize the pose.'
    detail: /portfolio/Kinect_Lab.html
    youtube: https://youtu.be/XqoOjGg4apQ
    tag: product

  - name: CM_Realtime_Engine
    title: CM Engine
    thumb: https://i.loli.net/2019/03/06/5c7f2b6847cb1.gif
    description: 'This project is an engine project I am working during the realtime rendering class. The first part focus on making an independent platform supports OpenGL & DirectX. The second part will focus on C++, Direct3D 11 API, and HLSL.'
    detail: /portfolio/CM_Engine.html
    github: https://github.com/lishtys/CM_Realtime_Engine
    tag: project

  - name: Meaty_McSkin_Bones
    title: Meaty McSkin Bones
    thumb: https://chenmi-ink-1252570167.cos.na-siliconvalley.myqcloud.com/_Works/MeatyMcSkinBones.png
    description: 'Meaty McSkinBones is a single-player puzzle/platformer where the character is split into three separate bodies. They each have unique abilities or can work together to solve puzzles and traverse the environment.'
    detail: https://www.meatymcskinbones.com/
    youtube: https://www.youtube.com/watch?v=JuyxBguA4qQ
    page: https://www.meatymcskinbones.com/
    steam: https://store.steampowered.com/app/1046370/Meaty_McSkinBones/
    tag: product

  - name: The_Red_Moon
    title: The Red Moon
    thumb: https://chenmi-ink-1252570167.cos.na-siliconvalley.myqcloud.com/_Works/RedMoonCover.PNG
    description: 'The Red Moon is a digital board game about Town Building, Alliances, and Magic made in Unity with MySQL'
    detail: /portfolio/Red_Moon.html
    youtube: https://youtu.be/XqoOjGg4apQ
    tag: project
      
  - name: Elec_Force
    title: Elec Force
    thumb: https://chenmi-ink-1252570167.cos.na-siliconvalley.myqcloud.com/_Works/Elecforce.JPG
    description: 'The theme of GGJ 2018 is transmission. So we use electrons as main characters. Best Doodles On Global Game Jam 2018'
    detail: /portfolio/Elecforce.html
    tag: project
